apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-inference
  namespace: fraud-detection
  labels:
    app: fraud-detection
    component: inference
spec:
  type: ClusterIP
  selector:
    app: fraud-detection
    component: inference
  ports:
  - name: http
    port: 8005
    targetPort: 8005
    protocol: TCP
  - name: grpc
    port: 8006
    targetPort: 8006
    protocol: TCP
  - name: metrics
    port: 8007
    targetPort: 8007
    protocol: TCP
