apiVersion: v2
name: fraud-detection-inference
description: NVIDIA Triton Inference Server for Fraud Detection
type: application
version: 1.0.0
appVersion: "25.04"
keywords:
  - nvidia
  - triton
  - inference
  - fraud-detection
  - machine-learning
home: https://github.com/your-org/fraud-detection
sources:
  - https://github.com/your-org/fraud-detection
maintainers:
  - name: Your Team
    email: team@example.com
