apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-detection-models
  namespace: fraud-detection
  labels:
    app: fraud-detection
    component: storage
spec:
  accessModes:
    - ReadWriteOnce  # Single node access is sufficient for inference-only
  resources:
    requests:
      storage: 5Gi
  # storageClassName: <your-storage-class>  # Uncomment if you need to specify
