# Secret 1: NGC API Key (for environment variable)
# This is a generic secret used to pass NGC_API_KEY as an environment variable
apiVersion: v1
kind: Secret
metadata:
  name: ngc-api-key
  namespace: fraud-detection
type: Opaque
stringData:
  NGC_API_KEY: "YOUR_NGC_API_KEY_HERE"  # Replace with your actual NGC API key

---
# Secret 2: Docker Registry Credentials (for image pull)
# This is a dockerconfigjson secret used by imagePullSecrets
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: fraud-detection
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "nvcr.io": {
          "username": "$oauthtoken",
          "password": "YOUR_NGC_API_KEY_HERE",
          "auth": "BASE64_OF_$oauthtoken:YOUR_NGC_API_KEY"
        }
      }
    }

# ============================================================================
# CREATION METHODS
# ============================================================================

# Method 1: Create both secrets using kubectl (RECOMMENDED)
# ----------------------------------------------------------
# kubectl create secret generic ngc-api-key \
#   --from-literal=NGC_API_KEY=YOUR_NGC_API_KEY \
#   --namespace=fraud-detection
#
# kubectl create secret docker-registry docker-registry-secret \
#   --docker-server=nvcr.io \
#   --docker-username='$oauthtoken' \
#   --docker-password=YOUR_NGC_API_KEY \
#   --namespace=fraud-detection

# Method 2: If you already have docker-registry-secret in OpenShift
# ------------------------------------------------------------------
# You only need to create the ngc-api-key secret:
#
# kubectl create secret generic ngc-api-key \
#   --from-literal=NGC_API_KEY=YOUR_NGC_API_KEY \
#   --namespace=fraud-detection

# Method 3: Extract NGC_API_KEY from existing docker-registry-secret
# -------------------------------------------------------------------
# If your docker-registry-secret already exists, extract the password:
#
# NGC_KEY=$(kubectl get secret docker-registry-secret -n fraud-detection \
#   -o jsonpath='{.data.\.dockerconfigjson}' | base64 -d | \
#   jq -r '.auths["nvcr.io"].password')
#
# kubectl create secret generic ngc-api-key \
#   --from-literal=NGC_API_KEY=$NGC_KEY \
#   --namespace=fraud-detection
#
# For OpenShift, you can also link the secret to the default service account:
# oc secrets link default docker-registry-secret --for=pull -n fraud-detection
